### ISSUE TITLE
Convert problems with big emails

### ISSUE THREAD

**Issue by redbrain17** [adb014/nsf2x#1] opened 2017-03-23 15:44 UTC
I'am using nsf2x to convert a lot of mails to mbox format. On some mails its failing I assume because the mails are to big ( > 20MB)
here the related logs:

```
INFO : Lotus Notes NSF file to EML, MBOX and PST file converter.
INFO : Contact dbateman@free.fr for more information.

ERROR : Error connecting to Lotus !
ERROR : Exception (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'NotesSession', 'Notes-Fehler: Die Kennwortabfrage wurde vom Benutzer abgebrochen', None, 0, -2147217504), None) :
ERROR : Check the Notes password and that NSF2X and Notes use the same architecture

INFO : Connection to Notes established

INFO : Starting Convert : 2017-03-23 14:59:10.133820

INFO : End of convert : 2017-03-23 14:59:10.147820

INFO : Starting Convert : 2017-03-23 14:59:13.396820

INFO : End of convert : 2017-03-23 14:59:13.410820

INFO : Starting Convert : 2017-03-23 15:01:59.568820

INFO : Converting : I:\a_ograut.nsf 
INFO : Starting MIME encoding of messages
ERROR : Error calling MIMEConvertCDParts(3644)
ERROR : Can not convert message 19576 to MIME
ERROR : #### Subject : Spy Tracer for GSM Trace Modul
ERROR : Error calling MIMEConvertCDParts(3644)
ERROR : Can not convert message 19577 to MIME
ERROR : #### Subject : Spy Tracer for GSM Trace Modul
INFO : Starting importation of EML messages into mailbox
INFO : Creating directory C:\Users\OGR\Documents\a_ograut
INFO : Opening MBOX file - C:\Users\OGR\Documents\a_ograut\Sent.mbox
ERROR : Exception for message 3259 ((-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'NotesMIMEEntity', 'Out of memory', None, 0, -2147217503), None)) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 946, in realConvert
  File "nsf2x.py", line 1378, in WriteMIMEOutput
  File "nsf2x.py", line 1253, in WriteMIMEChildren
  File "nsf2x.py", line 1227, in WriteMIMEChildren
  File "C:\Logiciel\WinPython-32bit-3.4.4.4Qt5\python-3.4.4\lib\site-packages\win32com\client\dynamic.py", line 516, in __getattr__
pywintypes.com_error: (-2147352567, 'Ausnahmefehler aufgetreten.', (0, 'NotesMIMEEntity', 'Out of memory', None, 0, -2147217503), None)

ERROR : #### Subject : TSC and SML Traces -  problems sending DCTs to certain SCMs
INFO : Opening MBOX file - C:\Users\OGR\Documents\a_ograut\Inbox.mbox

```

**Comment by adb014** [comment] 2017-03-27 11:34
You are the second person that has contacted me about this issue.

NSF2X relies on the convertMime function of Lotus Notes to do the heavy lift for the conversion to EML files, which then have a header line prepended for conversion to MBOX. So there might be little I can do about the issue.

Looking around the various Lotus sites, I saw a suggestion that there might be a memory leak in some of the Lotus code, and reinitializing the COM and C-DLL interfaces to Lotus might help resolve this problem.

I don't seem to have this issue; Perhaps my version of Lotus doesn't leak or just that I don't seem to have any mails that tigger the problem. So could you run a small test for me to see if there its worth my while trying to fix this issue. Could you do the following

1. Identify the mail that is causing an issue
2. Copy it to an empty NSF file, so that the NSF file contains only this message
3. Relaunch Lotus, to clear any potential memory leaks
4. Run NSF2X on the new NSF file and see if the OutOfMemory error still occurs

If it doesn't then I can try to modify NSF2X to fix the issue. If the problem isn't resolved then there seems that there will be little NSF2X can do to fix the issue.

In any case an alternative to get the handful of mails out of Lotus that NSF2X doesn't convert, is to find them in the Lotus interface and drag them to the desktop. They will then be in EML format. Add the lines

    /n
    From <ADDR> Date <DATE>/n

to the start of the EML file (where is /n is a newline) and then add it to the MBOX file that NSF2X created.

D.

**Comment by adb014** [comment] 2017-04-18 14:20
No reponse for 3 weeks, So I'm closing this issues. If you can run the tests I asked for and see if the OutOfMemory problem still occurs with a smaller NSF file, I'm still interested in the results

D.

**Closed by adb014** 2017-04-18 14:20 UTC
