### ISSUE TITLE
pywintypes.com_error: (-2147221164, 'Klasse is niet geregistreerd', None, None)

### ISSUE THREAD

**Issue by boyke** [adb014/nsf2x#7] opened 2017-09-26 07:14 UTC
INFO : Opening PST file - <FILE>
INFO : Starting importation of EML messages into mailbox
ERROR : Exception for message 0 ((-2147221164, 'Klasse is niet geregistreerd', None, None)) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 975, in realConvert
  File "C:\Logiciel\nsf2x\mapiex.py", line 248, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 88, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 317, in MimeToMapi
pywintypes.com_error: (-2147221164, 'Klasse is niet geregistreerd', None, None)

Some background information:

OS: Windows 10 x64
IBM Notes: Release 9.0.1FP8 (32 bits)
Outlook: 2016 (Click-to-Run/Office 365 32 bits)

I installed nsf2x with Administrator privileges, but can't find HKLM\SOFTWARE\Microsoft\Office\**16.0**\ClickToRun\REGISTRY\MACHINE\Software\Classes\

**Comment by adb014** [comment] 2017-10-12 13:05
This is effectively a problem with the registry and ClickToRun. NSF2X can not find the implementation of MAPI and in particular the IConverterSession function needed for the importation of EML files to Outlook.

The installer of NSF2X attempts to patch the registry to allow the use of NSF2X, and if it did it will display a HUGE warning message explaining the issue. The issue is explained inthis blog posting

https://blogs.msdn.microsoft.com/stephen_griffin/2014/04/21/outlook-2013-click-to-run-and-com-interfaces/

So I have a number of questions :

- Did you get the huge warning from the NSF2X installer ?
- Can you search the registry for "Office" and identify exactly where your ClickToRun version of Outlook stores its values ?

 I can't test Click2Run as I don't have access to a machine with it. If you can respond to the questions above I think I can make a version of the NSF2X installer that will work

D.

**Comment by adb014** [comment] 2017-10-12 13:06
http://www.advancedinstaller.com/forums/viewtopic.php?t=31293

discusses the registry changes for ClockToRun versions of Outlook

D.

**Comment by adb014** [comment] 2017-10-12 14:12
What does the registry value

HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\OUTLOOK.EXE

have as its value ?

**Comment by boyke** [comment] 2017-10-12 21:16
1. No huge warning (as far as I can remember)
2. Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\ClickToRun
3. C:\Program Files (x86)\Microsoft Office\Root\Office16\OUTLOOK.EXE

**Comment by GuidoDr** [comment] 2017-10-23 13:57
I had the same error (same OS, same Notes and Outlook version), only the error message was in german.
With the following registry hack I solved the problem and was able to sucessfully convert my notes archive to outlook. I created a cmd file (see attached .txt file which has to be renamed to a .cmd or .bat in order to execute it) with the below content and executed it as administrator.
After wards nsf2x did run without any problem.

rem For Office 32-bit on Windows 64-bit:
rem IConverterSession
reg copy HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} HKLM\SOFTWARE\Classes\Wow6432Node\CLSID\{4E3A7680-B77A-11D0-9DA5-00C04FD65685} /s /f
rem IMimeMessage
reg copy HKLM\SOFTWARE\Microsoft\Office\ClickToRun\REGISTRY\MACHINE\Software\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} HKLM\SOFTWARE\Classes\Wow6432Node\CLSID\{9EADBD1A-447B-4240-A9DD-73FE7C53A981} /s /f
[nsf2x_fix.txt](https://github.com/adb014/nsf2x/files/1407359/nsf2x_fix.txt)

**Comment by adb014** [comment] 2017-10-23 18:43
I bit the bullet and installed an O365 version of office to try and debug this issue. The code I committed last week should address the C2R issues with Outlook 2013 in a C2R install, without needing to patch the registry. I’m however having an issue with MIME conversion and Outlook 2016 in a C2R installation. 

As I’m still debugging I haven’t made a release. But if your inclined you can pull the fit version and run it from winpython with an install of at least version 220 of  pywin

I hope to figure out the problem with Outlook 2016 C2R and make a release soon


D.

**Comment by GuidoDr** [comment] 2017-10-24 06:13
I converted a small 340 MB (400 MB after wards) Notes archive yesterday in about 4 Minutes with 68 exceptions and 3342 documents OK.

And then a 11,5 GB Notes archive (now after the conversion 13,5 GB) that finished this morning after around 11 hours. It only had 929 exceptions and 161413 documents that were OK. 
So it went quite well and a very big thank you for your good work!

Most of the exceptions were ignoring messages ...without MIME body, so I am fine with that.
And a few were skipped with "probably not a message", also fine.

And five messages had this unkown error. I will try to find these messages in the DB in order to check what might be different with them.

ERROR : Exception for message 86160 ((-2147467259, 'Unbekannter Fehler', None, None)) :
ERROR : Traceback (most recent call last):
  File "nsf2x.py", line 975, in realConvert
  File "C:\Logiciel\nsf2x\mapiex.py", line 248, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 88, in ImportEML
  File "C:\Logiciel\nsf2x\mapiex.py", line 321, in MimeToMapi
pywintypes.com_error: (-2147467259, 'Unbekannter Fehler', None, None)

**Comment by adb014** [comment] 2017-10-24 12:08
The "Unknown Error" is almost certainly from the python implementation of the windows IStream in win32com.util. Windows sometimes calls the IStream.CopyTo method with N>2^32 which falles and the COM interface gives this error. The version of mapiex.py I uploaded last week has a fix for this as well, though still no release

D.

**Comment by adb014** [comment] 2018-02-02 16:02
The V1.3.5 version I just uploaded might fix this problem

**Comment by adb014** [comment] 2018-05-17 13:49
Closing as the problem seems fixed

**Closed by adb014** 2018-05-17 13:49 UTC
